CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_no VARCHAR(100) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    product_type VARCHAR(20) NOT NULL,
    base_premium INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_policies_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id),

    CONSTRAINT chk_policy_product_type
        CHECK (product_type IN ('TERM', 'ULIP', 'ENDOWMENT')),

    CONSTRAINT chk_policy_base_premium
        CHECK (base_premium > 0),

    CONSTRAINT chk_policy_status
        CHECK (status IN ('Active', 'Lapsed', 'Pending'))
);

CREATE TABLE claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_no VARCHAR(100) NOT NULL UNIQUE,
    policy_id BIGINT NOT NULL,
    amount INTEGER NOT NULL,
    urgency VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_claims_policy
        FOREIGN KEY (policy_id)
        REFERENCES policies(id),

    CONSTRAINT chk_claim_amount
        CHECK (amount > 0),

    CONSTRAINT chk_claim_urgency
        CHECK (urgency IN ('HIGH', 'MEDIUM', 'LOW')),

    CONSTRAINT chk_claim_status
        CHECK (status IN ('SUBMITTED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE riders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE policy_riders (
    policy_id BIGINT NOT NULL,
    rider_id BIGINT NOT NULL,

    PRIMARY KEY (policy_id, rider_id),

    CONSTRAINT fk_policy_riders_policy
        FOREIGN KEY (policy_id)
        REFERENCES policies(id),

    CONSTRAINT fk_policy_riders_rider
        FOREIGN KEY (rider_id)
        REFERENCES riders(id)
);

